### PR TITLE
Create CONTRIBUTING.md

### LINKED ISSUE #1: Add CONTRIBUTING.md
In the spirit of getting more contributors to the project, the above document would be appreciated.

### PR DESCRIPTION
**Pull request by Kunal1198**
Fixes #1 
Added `CONTRIBUTING.md`

### CODE REVIEW

**Review by gridhead — CHANGES_REQUESTED** [review]
You are requested to kindly explore and learn more about the topics which can be added to CONTRIBUTING.md. Add those topics once you have acquired them.

**Comment by Kunal1198** [comment]
Hi @t0xic0der ,can you please tell me what are some topics which need to be added....as I have already added the steps.

**Comment by gridhead** [comment]
As I have specified before, please take your time and explore about the potential additions.

**Comment by Kunal1198** [comment]
Hi @t0xic0der Please review the changes done.

**Review by gridhead — APPROVED** [review]
Nicely written.

**Pull request merged**
